### ISSUE TITLE
Do you have a resnet equivalent of GraphTensor

### ISSUE THREAD

**Issue by thegodone** [akensert/molgraph#10]
so I want to add the first convolution result "1. x = GCNConv(x)" into the second convolution projection like "2. x+= GCNConv(x)"

**Comment by akensert** [comment]
Like this

```python
class MyModel(tf.keras.Model):
    def __init__(self):
        self.conv_1 = GCNConv(128)
        self.conv_2 = GCNConv(128)
    def call(self, tensor: GraphTensor):
        x = self.conv_1(tensor)
        x += self.conv_2(x)
       return x
```
?

$x \leftarrow Conv_{1}(x) + Conv_{2}((Conv_{1}(x))$

**Comment by akensert** [comment]
The output of a Conv layer is always a new `GraphTensor` instance. So e.g. `x_1` does not change.

Same when you do `gt_2 = gt_1.update({'node_feature': updated_node_feature})` , `gt_1` does not change; i.e. its attributes are not changed internally,  this is important as it will help tensorflow with the tracking.
