### ISSUE TITLE
OCHEM integration: pickle preprocessing

### ISSUE THREAD

**Issue by thegodone** [akensert/molgraph#11]
I try to pickle the node and edge preprocessing and there is an error.
```
import pickle as pk

params = {'np':node_preprocessing,'ep':edge_preprocessing}

pk.dump(params,open('modelparameters.pk','wb')) 
```
AttributeError: Can't pickle local object 'PreprocessingLayer.make_adapt_function.<locals>.adapt_step'

current workaround: save the train dataset and regenerate the train_ds and adapt the node and edge preprocessings

**Comment by akensert** [comment]
Seems to be an issue related to `tf.keras.ProcessingLayer` (which the molgraph preprocessing layers are inhereting from).

[I found this](https://stackoverflow.com/questions/72711686/cannot-pickle-tensorflow-preprocessing-layer-attributeerror-cant-pickle-local), related problem.
