### ISSUE TITLE
OCHEM integration: Apply on new datataset

### ISSUE THREAD

**Issue by thegodone** [akensert/molgraph#12]
I try to infere new points (I recreate my model based on save weights) using saved model, but I see some variations on few models cases can you check this behaviour.

model use the following preprocessings: 
```
        self.node_preprocess = node_preprocessing
        self.edge_preprocess = edge_preprocessing
        self.LPE = LaplacianPositionalEncoding()
```
maybe LPE is not saved properly in the weights ?

**Comment by akensert** [comment]
Laplacian positional encoding introduce som randomness (random flipping of signs). Is that what you are observing? Can you try to clarify what the problem is? :)

You can check that the weights have been loaded correctly by looking at the actual weights of the model before and after it has been loaded. Let me know if you need any further assistance with that.

**Comment by akensert** [comment]
I'm currently in the process of writing more tests (this time with unittest), to make make sure things are working as expected. Although I'm already running tests, it is not really extensive enough. Regarding model saving specifically: I think it is likely that it works well as I've been testing it out a lot (especially offline). However, I can't be 100% sure everything works as expected; I think it is great, and I'm also grateful, that you are trying things out :)

**Comment by thegodone** [comment]
Yes, unittest is a must to have. Happy to help there. Is the "Laplacian positional encoding" randomness part is like in dropout only on training ? If it is not the case I see it like a simple augmentation technic that can be leverage for variability of prediction. But I did not notice this aspect in any papers this is somehow not explored yet or I miss one paper comment ?

**Comment by akensert** [comment]
They bring it up in the paper. As the sign out the eigen vectors can be either negative or positive (though only one of them are computed arbitrarily) it is strongly recommended to randomly flip them. You are right that it seems to be done during training, and I guess you could also see it as some kind of data augmentation. I should add a `if training: ... perform random sign flip ...`

From e.g. [this paper](https://arxiv.org/pdf/2012.09699.pdf):

"Although these eigenvectors have multiplicity occuring due
to the arbitrary sign of eigenvectors, we randomly flip the
sign of the eigenvectors during training, following Dwivedi
et al. (2020)."

**Comment by akensert** [comment]
> it was my filling. So basically you have two only two possible results + or - ? What is the correct answer the mean ?

The mean would be 0, I would say. The correct answer is both (either). Hopefully the model will learn both. Consequently, during prediction time, either the outcomes (of the sign flipping) should will work well.
