### ISSUE TITLE
Positional Encoding questions ?

### ISSUE THREAD

**Issue by thegodone** [akensert/molgraph#13]
Which one of the following PE's can be added to the current code containing I guess LPE ?

https://github.com/cptq/SignNet-BasisNet/blob/main/GraphPrediction/data/molecules.py

This is from this paper: https://arxiv.org/pdf/2202.13013.pdf

**Comment by akensert** [comment]
They use the Laplacian positional encoding. Looks like the same as `molgraph.layers.LaplacianPositionalEncoding`. I did not immediately see the random flipping of the sign of the eigen vectors, but I guess they will perform it later on in the model along with a linear transformation.
