### ISSUE TITLE
nan in loss with those molecules

### ISSUE THREAD

**Issue by thegodone** [akensert/molgraph#18]
basically due to the     features.GasteigerCharge() that can be null few molecules with like whit  "P" atoms will produce nans during training. 
Can you replace the nan features for those molecules by 0.0 in such case ?

**Comment by akensert** [comment]
This is the current implementation:

```python
@atom_features.register(name='gasteiger_charge')
class GasteigerCharge(Feature):
    def __call__(self, atom: Chem.Atom) -> float:
        mol = atom.GetOwningMol()
        rdPartialCharges.ComputeGasteigerCharges(mol)
        val = atom.GetDoubleProp('_GasteigerCharge')
        return val if val is not None else 0.0
```
Isn't it already taking care of it? Can you give me an example molecule that causes the issue and I'll look into it.

**Comment by thegodone** [comment]
this is a molecule that failed : ['OC[PH](CO)(CO)CO']
I add GasteigerCharges and it goes to nan I remove it and it works. I think the vales are not None but Nan.

**Comment by akensert** [comment]
```python
smiles = 'OCPH(CO)CO'
mol = molgraph.chemistry.molecule_from_string(smiles)
```
```
ValueError: Inputted `molecule` (None) is invalid
```

**Comment by thegodone** [comment]
I fix the smiles in github issue page see upper
