### ISSUE TITLE
Planning for next models implementation

### ISSUE THREAD

**Issue by thegodone** [akensert/molgraph#26]
I have more time those days to review and upgrade my codes (kgcnn) now has 23 models implemented. I would like to see if we can find time to implement not all of them but max 5 of the best ones. what do you think ?

for ESOL:
![image](https://github.com/akensert/molgraph/assets/1186658/c9144a70-7f57-4ec7-ab4c-b7e75552eb18)
for Fresolv:
![image](https://github.com/akensert/molgraph/assets/1186658/424cc331-0adf-4e61-a910-411f064150a1)

By the way you can now only contact me using my gmail.com email I am moving to another company.
Please let me know your point of view on that.

Especially DGIN looks encouraging compare to GIN version and close to DMPNN. 

thanks

Guillaume

**Comment by akensert** [comment]
Hi @thegodone, thanks for the info! :)

If time allows, I could look into the most promising/interesting ones. Not sure though who those are. Given DMPNN, AttentiveFP, GATv2, etc. are already implemented with molgraph, I wonder whether there are any other models worth implementing? 

Have you tried the DMPNN or AttentiveFP of molgraph? How are they performing in comparison? (They might need some hyper-parameter fine-tuning or tweaks to perform well.)

Based on the paper I read on DGIN (think it was the original DGIN paper, but not sure), it did not seem particularly interesting to me.

**Comment by soulios** [comment]
To piggyback on this, I find CMPNN useful.
