### ISSUE TITLE
Training based on the output of GradCAM?

### ISSUE THREAD

**Issue by vcanogil** [akensert/molgraph#27]
Is it possible using `molgraph` to write a model that could be trained based on the output of it's GradCAM map?
I.e. a GNN that takes a molecule and adjusts its weight based on the heatmap it produces?

**Comment by akensert** [comment]
Hi @vcanogil, not sure how this would be done, and also why? 

The saliency maps are basically gradients of the output with respect to the data (the node features). I don't see how you would then be able to obtain gradients of that with respect to the weights. Perhaps I've misunderstood?

**Comment by vcanogil** [comment]
Never mind, after thinking about it some, I don't think it'll make sense either
