### ISSUE TITLE
Do you have a directed graph implementation like DiGIN or ChemProp ?

### ISSUE THREAD

**Issue by thegodone** [akensert/molgraph#3]
I am looking for the Directed GIN / Directed MPNN version :

https://www.mdpi.com/1420-3049/26/20/6185

thanks 

GG

**Comment by thegodone** [comment]
Hi Alexander, this is the correct implementation of suming on source edge following by removing the destination edge contribution.

is it possible to have a layer too like MPNNConv ? and a true model example like ESOL please ? I want to make benchmarks versus KGCNN on performance of the models.

**Comment by akensert** [comment]
Hi @thegodone. Thanks. (The directed MPNN/GIN implementations should correspond to what I wrote above.) 

Regarding implementation of a layer: I will look into it.

**Comment by thegodone** [comment]
Did you also use "directed edge" data in order to change the data
generation process from undirected into only directed ?

Le ven. 7 avr. 2023 à 11:59, Alexander Kensert ***@***.***> a
écrit :

**Comment by akensert** [comment]
Not sure what you mean exactly (sorry). There is currently no module that generates directed graphs. ``MolecularGraphEncoder`` generates (small) molecular graphs which are undirected; or you can actually think of them as directed graphs wherein edges `u -> w` = `w -> u`. 

And the existing gnn layers can handle directed graphs. For instance, you can read one of the well known citation dataset (note: no existing module in molgraph to read those datasets in) and then fit a gnn model to them.

The ``GraphTensor`` which is produced by ``MolecularGraphEncoder`` looks something like this (let's assume you are encoding the molecule `CC` and bond type is a onehot encoding [single, double, triple]):

```
print(graph_tensor.edge_dst)
print(graph_tensor.edge_src)
print(graph_tensor.edge_feature)
>>> tf.Tensor([0 1], shape=(2,), dtype=int32)
>>> tf.Tensor([1 0], shape=(2,), dtype=int32)
>>> tf.Tensor(
>>>    [[1. 0. 0.]
>>>    [[1. 0. 0.]], shape=(2, 3), dtype=float32)
```
So even though there is only one bond, two edges exist (one in each direction); in the case of molecules they should be the same.

Btw, I'm happy to start to think about directed graph problems. So far I've been focusing mostly (almost exclusively) on undirected graphs.

(Apologies if I'm completely off the track here, and I'm not answering your question at all.)
