### ISSUE TITLE
is there a way to go a deep clone copy of the graphTensor ?

### ISSUE THREAD

**Issue by thegodone** [akensert/molgraph#9]
I want to clone the graphTensor initial inputs can it be done in a class model ?

**Comment by akensert** [comment]
> I want to clone the graphTensor initial inputs can it be done in a class model ?

I'm not entirely sure what you mean

This will create a new instance of `graph_tensor` with same values:
```python
graph_tensor_2 = graph_tensor 
```
if you change `graph_tensor_2` nothing happens to `graph_tensor`

**Comment by akensert** [comment]
> I want to clone the graphTensor initial inputs can it be done in a class model ?

Like this:

```python
graph_tensor_initial = graph_tensor 

# this will create a new instance of graph_tensor.
graph_tensor = graph_tensor.update({'node_feature': updated_node_feature})

```
?
